### ISSUE TITLE
Bug:  vitdet-faster_rcnn,get Masks length: 0.

### ISSUE THREAD

**Issue by ZhaoBaymax** [alibaba/EasyCV#316]
when i do vitdet-faster_rcnn, i get this error at epoch 12. The previous training was normal, but the map was 0. 

dateset：  http://pai-vision-data-hz.oss-cn-zhangjiakou.aliyuncs.com/data/small_coco_demo/small_coco_demo.tar.gz

I also had this problem with my own data set, but with the beginning of epoch0.

2023-05-24 21:35:57,648 - easycv - INFO - Epoch(val) [12][5]	CocoDetectionEvaluator_DetectionBoxes_Precision/mAP: 0.0000, DetectionBoxes_Precision/mAP: 0.0000, DetectionBoxes_Precision/mAP@.50IOU: 0.0000, DetectionBoxes_Precision/mAP@.75IOU: 0.0000, DetectionBoxes_Precision/mAP (small): 0.0000, DetectionBoxes_Precision/mAP (medium): 0.0000, DetectionBoxes_Precision/mAP (large): 0.0000, DetectionBoxes_Recall/AR@1: 0.0000, DetectionBoxes_Recall/AR@10: 0.0000, DetectionBoxes_Recall/AR@100: 0.0000, DetectionBoxes_Recall/AR@100 (small): 0.0000, DetectionBoxes_Recall/AR@100 (medium): 0.0000, DetectionBoxes_Recall/AR@100 (large): 0.0000, CocoMaskEvaluator_DetectionMasks_Precision/mAP: 0.0000, DetectionMasks_Precision/mAP: 0.0000, DetectionMasks_Precision/mAP@.50IOU: 0.0000, DetectionMasks_Precision/mAP@.75IOU: 0.0000, DetectionMasks_Precision/mAP (small): 0.0000, DetectionMasks_Precision/mAP (medium): 0.0000, DetectionMasks_Precision/mAP (large): 0.0000, DetectionMasks_Recall/AR@1: 0.0000, DetectionMasks_Recall/AR@10: 0.0000, DetectionMasks_Recall/AR@100: 0.0000, DetectionMasks_Recall/AR@100 (small): 0.0000, DetectionMasks_Recall/AR@100 (medium): 0.0000, DetectionMasks_Recall/AR@100 (large): 0.0000
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 20/20, 7.0 task/s, elapsed: 3s, ETA:     0s
creating index...
index created!
Loading and preparing annotation results...
DONE (t=%0.2fs) 0.00039196014404296875
creating index...
index created!

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/hm/zhaosf/EasyCV/tools/train.py:319 in <module>                        │
│                                                                              │
│   316                                                                        │
│   317                                                                        │
│   318 if __name__ == '__main__':                                             │
│ ❱ 319 │   main()                                                             │
│   320                                                                        │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/tools/train.py:307 in main                            │
│                                                                              │
│   304 │   │   data_loaders = [dataset.get_dataloader()]                      │
│   305 │                                                                      │
│   306 │   # # add an attribute for visualization convenience                 │
│ ❱ 307 │   train_model(                                                       │
│   308 │   │   model,                                                         │
│   309 │   │   data_loaders,                                                  │
│   310 │   │   cfg,                                                           │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/apis/train.py:312 in train_model               │
│                                                                              │
│   309 │   │   runner.logger.info(f'load checkpoint from {cfg.load_from}')    │
│   310 │   │   runner.load_checkpoint(cfg.load_from)                          │
│   311 │                                                                      │
│ ❱ 312 │   runner.run(data_loaders, cfg.workflow, cfg.total_epochs)           │
│   313                                                                        │
│   314                                                                        │
│   315 def get_skip_list_keywords(model):                                     │
│                                                                              │
│ /home/hm/anaconda3/envs/zhaosf-thermal/lib/python3.8/site-packages/mmcv/runn │
│ er/epoch_based_runner.py:136 in run                                          │
│                                                                              │
│   133 │   │   │   │   for _ in range(epochs):                                │
│   134 │   │   │   │   │   if mode == 'train' and self.epoch >= self._max_epo │
│   135 │   │   │   │   │   │   break                                          │
│ ❱ 136 │   │   │   │   │   epoch_runner(data_loaders[i], **kwargs)            │
│   137 │   │                                                                  │
│   138 │   │   time.sleep(1)  # wait for some hooks like loggers to finish    │
│   139 │   │   self.call_hook('after_run')                                    │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/runner/ev_runner.py:112 in train               │
│                                                                              │
│   109 │   │   │   self.call_hook('after_train_iter')                         │
│   110 │   │   │   self._iter += 1                                            │
│   111 │   │                                                                  │
│ ❱ 112 │   │   self.call_hook('after_train_epoch')                            │
│   113 │   │                                                                  │
│   114 │   │   self._epoch += 1                                               │
│   115                                                                        │
│                                                                              │
│ /home/hm/anaconda3/envs/zhaosf-thermal/lib/python3.8/site-packages/mmcv/runn │
│ er/base_runner.py:317 in call_hook                                           │
│                                                                              │
│   314 │   │   │   │   "before_train_epoch".                                  │
│   315 │   │   """                                                            │
│   316 │   │   for hook in self._hooks:                                       │
│ ❱ 317 │   │   │   getattr(hook, fn_name)(self)                               │
│   318 │                                                                      │
│   319 │   def get_hook_info(self) -> str:                                    │
│   320 │   │   # Get hooks info in each stage                                 │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/hooks/eval_hook.py:80 in after_train_epoch     │
│                                                                              │
│    77 │   │   │   else:                                                      │
│    78 │   │   │   │   results = single_gpu_test(                             │
│    79 │   │   │   │   │   runner.model, self.dataloader, mode=self.mode, sho │
│ ❱  80 │   │   │   self.evaluate(runner, results)                             │
│    81 │                                                                      │
│    82 │   def add_visualization_info(self, runner, results):                 │
│    83 │   │   if runner.visualization_buffer.output.get('eval_results',      │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/hooks/eval_hook.py:107 in evaluate             │
│                                                                              │
│   104 │   │   │   eval_res = self.dataloader.evaluate(                       │
│   105 │   │   │   │   results, logger=runner.logger, **self.eval_kwargs)     │
│   106 │   │   else:                                                          │
│ ❱ 107 │   │   │   eval_res = self.dataloader.dataset.evaluate(               │
│   108 │   │   │   │   results, logger=runner.logger, **self.eval_kwargs)     │
│   109 │   │                                                                  │
│   110 │   │   for name, val in eval_res.items():                             │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/datasets/detection/raw.py:102 in evaluate      │
│                                                                              │
│    99 │   │   │   │   │   │   │   │   │      pred_folder, categories))       │
│   100 │   │   │   else:                                                      │
│   101 │   │   │   │   eval_result.update(                                    │
│ ❱ 102 │   │   │   │   │   evaluator.evaluate(results, groundtruth_dict))     │
│   103 │   │                                                                  │
│   104 │   │   return eval_result                                             │
│   105                                                                        │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/core/evaluation/base_evaluator.py:27 in        │
│ evaluate                                                                     │
│                                                                              │
│   24 │   │   self._metric_names = metric_names                               │
│   25 │                                                                       │
│   26 │   def evaluate(self, prediction_dict, groundtruth_dict, **kwargs):    │
│ ❱ 27 │   │   eval_res = self._evaluate_impl(prediction_dict, groundtruth_dic │
│   28 │   │   │   │   │   │   │   │   │      **kwargs)                        │
│   29 │   │   if eval_res is None:                                            │
│   30 │   │   │   return                                                      │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_evaluation.py:668 in      │
│ _evaluate_impl                                                               │
│                                                                              │
│    665 │   │   │   │   'detection_scores': detection_scores,                 │
│    666 │   │   │   │   'detection_classes': detection_classes,               │
│    667 │   │   │   }                                                         │
│ ❱  668 │   │   │   self.add_single_detected_image_info(image_id, detection_d │
│    669 │   │                                                                 │
│    670 │   │   eval_dict = self._evaluate()                                  │
│    671 │   │   self.clear()                                                  │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_evaluation.py:510 in      │
│ add_single_detected_image_info                                               │
│                                                                              │
│    507 │   │   │   standard_fields.DetectionResultFields.detection_masks,    │
│    508 │   │   │   detection_masks)                                          │
│    509 │   │   self._detection_masks_list.extend(                            │
│ ❱  510 │   │   │   coco_tools.ExportSingleImageDetectionMasksToCoco(         │
│    511 │   │   │   │   image_id=image_id,                                    │
│    512 │   │   │   │   category_id_set=self._category_id_set,                │
│    513 │   │   │   │   detection_masks=detection_masks,                      │
│                                                                              │
│ /home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_tools.py:613 in           │
│ ExportSingleImageDetectionMasksToCoco                                        │
│                                                                              │
│   610 │   assert len(detection_classes.shape) == 1 and len(detection_scores. │
│   611 │   │   'All entries in detection_classes and detection_scores expecte │
│   612 │   num_boxes = detection_classes.shape[0]                             │
│ ❱ 613 │   assert num_boxes == len(detection_masks) == detection_scores.shape │
│   614 │   │   'Corresponding entries in detection_classes, ' \               │
│   615 │   │   'detection_scores and detection_masks should have ' \          │
│   616 │   │   'compatible lengths and shapes ' \                             │
╰──────────────────────────────────────────────────────────────────────────────╯
AssertionError: Corresponding entries in detection_classes, detection_scores and
detection_masks should have compatible lengths and shapes Classes length: 21.  
Masks length: 0. Scores length: 21

Process finished with exit code 1

**Checklist**

**To Reproduce**
* What command or script did you run?
python tools\train.py configs/detection/vitdet/vitdet_faster_rcnn_100e.py --work_dir easycv/vitdet  --fp16

* Did you make any modifications on the code or config? Did you understand what you have modified?
* What dataset did you use?
in lsj_coco_instance.py , i change image_size = (640, 640). 
use dataset form  http://pai-vision-data-hz.oss-cn-zhangjiakou.aliyuncs.com/data/small_coco_demo/small_coco_demo.tar.gz

**Environment**
* Please run python easycv/utils/collect_env.py to collect necessary environment information and paste it here.
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)
sys.platform: linux
Python: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:53:36) [GCC 9.4.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GPU 0,1: NVIDIA GeForce RTX 3090
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2+cu111
OpenCV: 4.6.0
MMCV: 1.7.1
EasyCV: 0.11.1

install pytorch by pip

**Comment by ZhaoBaymax** [comment]
Traceback (most recent call last):
  File "/home/hm/zhaosf/EasyCV/tools/train.py", line 319, in <module>
    main()
  File "/home/hm/zhaosf/EasyCV/tools/train.py", line 315, in main
    use_fp16=args.fp16)
  File "/home/hm/zhaosf/EasyCV/easycv/apis/train.py", line 312, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/hm/anaconda3/envs/ev/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hm/zhaosf/EasyCV/easycv/runner/ev_runner.py", line 112, in train
    self.call_hook('after_train_epoch')
  File "/home/hm/anaconda3/envs/ev/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/hm/zhaosf/EasyCV/easycv/hooks/eval_hook.py", line 80, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/hm/zhaosf/EasyCV/easycv/hooks/eval_hook.py", line 108, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/hm/zhaosf/EasyCV/easycv/datasets/detection/raw.py", line 102, in evaluate
    evaluator.evaluate(results, groundtruth_dict))
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/base_evaluator.py", line 28, in evaluate
    **kwargs)
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_evaluation.py", line 668, in _evaluate_impl
    self.add_single_detected_image_info(image_id, detection_dict)
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_evaluation.py", line 517, in add_single_detected_image_info
    standard_fields.DetectionResultFields.detection_classes]))
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_tools.py", line 619, in ExportSingleImageDetectionMasksToCoco
    detection_scores.shape[0])
AssertionError: Corresponding entries in detection_classes, detection_scores and detection_masks should have compatible lengths and shapes Classes length: 13.  Masks length: 0. Scores length: 13
还是存在这个问题，这个可以修复吗？？
