### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by ZhaoBaymax** [alibaba/EasyCV#323]
Traceback (most recent call last):
  File "/home/hm/zhaosf/EasyCV/tools/train.py", line 319, in <module>
    main()
  File "/home/hm/zhaosf/EasyCV/tools/train.py", line 315, in main
    use_fp16=args.fp16)
  File "/home/hm/zhaosf/EasyCV/easycv/apis/train.py", line 312, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/hm/anaconda3/envs/ev/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hm/zhaosf/EasyCV/easycv/runner/ev_runner.py", line 112, in train
    self.call_hook('after_train_epoch')
  File "/home/hm/anaconda3/envs/ev/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/hm/zhaosf/EasyCV/easycv/hooks/eval_hook.py", line 80, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/hm/zhaosf/EasyCV/easycv/hooks/eval_hook.py", line 108, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/hm/zhaosf/EasyCV/easycv/datasets/detection/raw.py", line 102, in evaluate
    evaluator.evaluate(results, groundtruth_dict))
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/base_evaluator.py", line 28, in evaluate
    **kwargs)
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_evaluation.py", line 668, in _evaluate_impl
    self.add_single_detected_image_info(image_id, detection_dict)
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_evaluation.py", line 517, in add_single_detected_image_info
    standard_fields.DetectionResultFields.detection_classes]))
  File "/home/hm/zhaosf/EasyCV/easycv/core/evaluation/coco_tools.py", line 619, in ExportSingleImageDetectionMasksToCoco
    detection_scores.shape[0])
AssertionError: Corresponding entries in detection_classes, detection_scores and detection_masks should have compatible lengths and shapes Classes length: 13.  Masks length: 0. Scores length: 13
还是存在这个问题，这个可以修复吗？？

_Originally posted by @ZhaoBaymax in https://github.com/alibaba/EasyCV/issues/316#issuecomment-1595680194_

**Comment by zouxinyi0625** [comment]
您好，可以麻烦提供一下 运行的命令吗？
